import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleDashed } from "lucide-react";

const evidence = [
  ["Implemented", "Database-backed identity, opaque sessions, CSRF defense, tenant context, and PostgreSQL row-level policies."],
  ["Tested locally", "Locked API tests exercise account lifecycle, tenant invitation, authorization, decision workflow, and Ollama catalogue invariants."],
  ["Reproducible source", "Terraform describes AWS network, ECS, RDS, Redis, SES, S3, WAF, secrets, alarms, and DNS; container builds run as non-root."],
];
const pending = [
  "AWS production is gated on owner-approved provisioning and domain setup.",
  "Data integrity, restore drills, rollback rehearsal, and a 72-hour production observation remain release criteria.",
  "Customer and financial outcomes will be measured prospectively rather than asserted upfront.",
];

export default function CompanyProofPage() {
  return <main className="min-h-screen bg-fog px-5 py-12 text-ink"><article className="mx-auto max-w-5xl"><Link href="/" className="text-xs font-bold uppercase tracking-[0.2em] text-teal">Ambrosia</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.18em] text-teal">Company proof · evidence before claims</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-tight tracking-[-0.04em] sm:text-6xl">A focused product thesis with its limitations left visible.</h1><p className="mt-6 max-w-3xl text-base leading-7 text-ink/62">Ambrosia is building governed investment-decision infrastructure for professional teams. This page distinguishes code that exists, checks that have run, and production evidence that still must be earned.</p><section className="mt-12 grid gap-4 md:grid-cols-3">{evidence.map(([label, copy]) => <div key={label} className="rounded-xl border border-teal/25 bg-paper p-5"><CheckCircle2 className="h-5 w-5 text-teal" /><h2 className="mt-5 text-sm font-semibold">{label}</h2><p className="mt-2 text-sm leading-6 text-ink/58">{copy}</p></div>)}</section><section className="mt-8 rounded-2xl border border-line bg-paper p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-ink/45">Open evidence gates</p><ul className="mt-5 space-y-4">{pending.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-ink/62"><CircleDashed className="mt-1 h-4 w-4 shrink-0 text-amber-300" />{item}</li>)}</ul></section><section className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-line bg-paper p-6"><h2 className="text-lg font-semibold">Commercial hypothesis</h2><p className="mt-3 text-sm leading-6 text-ink/60">Teams of roughly 5–75 people will pay to reduce decision-preparation time while improving provenance, disagreement, accountability, and organizational memory. That remains a testable hypothesis until repeated paid use exists.</p></div><div className="rounded-xl border border-line bg-paper p-6"><h2 className="text-lg font-semibold">Capital purpose</h2><p className="mt-3 text-sm leading-6 text-ink/60">Financing would fund security validation, design-partner onboarding, measured workflow evaluation, and the operating controls required for a controlled beta—not unsupported promises of alpha.</p></div></section><Link href="/signup" className="focus-ring mt-10 inline-flex items-center gap-2 rounded-md bg-teal px-5 py-3 text-sm font-bold text-[#071411]">Evaluate the workflow <ArrowRight className="h-4 w-4" /></Link></article></main>;
}
