#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = ROOT / "packages" / "schemas" / "fixtures" / "mobile-control-plane.fixture.json"
OUTPUT_PATH = ROOT / "apps" / "mobile" / "src" / "generated" / "mobile-contract.ts"


def ts_string(value: str) -> str:
    return json.dumps(value)


def main() -> int:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    routes = contract["routes"]
    lines = [
        "// Generated by scripts/generate-mobile-contract-types.py. Do not edit manually.",
        "",
        'export const mobileContractVersion = "mobile-control-plane.v1" as const;',
        "",
        "export type MobileContractRoute = {",
        '  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";',
        "  path: string;",
        "  mobileModule: string;",
        "  clientFunction: string;",
        '  sourceOfTruth: "fastapi";',
        "  purpose: string;",
        "  mutating: boolean;",
        "  requiresServerConfirmation: boolean;",
        "};",
        "",
        "export const mobileContractRoutes = [",
    ]
    for route in routes:
        lines.extend(
            [
                "  {",
                f"    method: {ts_string(route['method'])},",
                f"    path: {ts_string(route['path'])},",
                f"    mobileModule: {ts_string(route['mobileModule'])},",
                f"    clientFunction: {ts_string(route['clientFunction'])},",
                '    sourceOfTruth: "fastapi",',
                f"    purpose: {ts_string(route['purpose'])},",
                f"    mutating: {str(route['mutating']).lower()},",
                f"    requiresServerConfirmation: {str(route['requiresServerConfirmation']).lower()}",
                "  },",
            ]
        )
    lines.extend(
        [
            "] as const satisfies readonly MobileContractRoute[];",
            "",
            "export const mobileContractRouteCount = mobileContractRoutes.length;",
            "",
        ]
    )
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} with {len(routes)} routes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
