#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = ROOT / "artifacts"


def run_check(command: list[str], cwd: Path) -> tuple[bool, str]:
    result = subprocess.run(command, cwd=str(cwd), capture_output=True, text=True)
    output = (result.stdout or "") + ("\n" + result.stderr if result.stderr else "")
    return result.returncode == 0, output.strip()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_latest_migration() -> str:
    migrations_dir = ROOT / "infra" / "db" / "migrations"
    migration_files = sorted(migrations_dir.glob("V*.sql"))
    if not migration_files:
        return "none"
    return migration_files[-1].name


def to_markdown(report: dict[str, object]) -> str:
    lines: list[str] = []
    lines.append("# Milestone M1 Readiness Report")
    lines.append("")
    lines.append(f"Generated: {report['generatedAt']}")
    lines.append(f"Milestone Target: {report['milestone']}")
    lines.append(f"Readiness: {'READY' if report['ready'] else 'NOT READY'}")
    lines.append(f"Estimated platform completion: {report['estimatedCompletionPct']}%")
    lines.append("")

    checks = report["checks"]
    lines.append("## Gate Summary")
    lines.append("")
    lines.append(f"- Migration/versioning gate: {'PASS' if checks['migrationVersioning']['passed'] else 'FAIL'}")
    lines.append(f"- Retrieval benchmark gate: {'PASS' if checks['retrievalBenchmark']['passed'] else 'FAIL'}")
    lines.append(f"- Scorecard runtime gate: {'PASS' if checks['scorecardRuntime']['passed'] else 'FAIL'}")
    lines.append("")

    lines.append("## Readiness Criteria")
    lines.append("")
    lines.append(f"- dbSchemaVersion: {report['context']['dbSchemaVersion']}")
    lines.append(f"- latest migration: {report['context']['latestMigration']}")
    lines.append(f"- retrieval recall rate: {report['context']['retrievalRecallRate']}")
    lines.append(f"- retrieval drift errors: {report['context']['retrievalDriftErrors']}")
    lines.append(f"- scorecard certification status: {report['context']['scorecardCertificationStatus']}")
    lines.append(f"- scorecard metrics count: {report['context']['scorecardMetricsCount']}")
    lines.append("")

    if report["errors"]:
        lines.append("## Blocking Issues")
        lines.append("")
        for error in report["errors"]:
            lines.append(f"- {error}")
        lines.append("")
    else:
        lines.append("## Blocking Issues")
        lines.append("")
        lines.append("- None")
        lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append("- This report is auto-generated by scripts/generate-m1-readiness.py.")
    lines.append("- M1 requires migration/versioning standardization and trustworthy metrics/scorecard runtime evidence.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    migration_ok, migration_output = run_check(
        [sys.executable, "scripts/verify-migrations.py"], ROOT
    )
    retrieval_ok, retrieval_output = run_check(
        [sys.executable, "packages/evals/run_retrieval_benchmark.py"],
        ROOT,
    )
    scorecard_ok, scorecard_output = run_check(
        [sys.executable, "scripts/verify-scorecard-runtime.py"],
        ROOT,
    )

    schema_version = read_json(ROOT / "infra" / "db" / "schema-version.json")
    retrieval_report = read_json(ARTIFACTS_DIR / "retrieval-benchmark.json")
    scorecard_report = read_json(ARTIFACTS_DIR / "scorecard-runtime.json")

    retrieval_passed = (
        retrieval_ok
        and retrieval_report.get("summary", {}).get("failedCases", 1) == 0
        and len(retrieval_report.get("driftErrors", [])) == 0
    )
    scorecard_passed = scorecard_ok and bool(scorecard_report.get("passed"))

    checks = {
        "migrationVersioning": {
            "passed": migration_ok,
            "command": "python scripts/verify-migrations.py",
        },
        "retrievalBenchmark": {
            "passed": retrieval_passed,
            "command": "python packages/evals/run_retrieval_benchmark.py",
        },
        "scorecardRuntime": {
            "passed": scorecard_passed,
            "command": "python scripts/verify-scorecard-runtime.py",
        },
    }

    passed_count = sum(1 for item in checks.values() if item["passed"])
    estimated_completion = round(78 + (passed_count / 3.0) * 7, 1)
    ready = passed_count == 3

    errors: list[str] = []
    if not migration_ok:
        errors.append("Migration/versioning gate failed")
    if not retrieval_passed:
        errors.append("Retrieval benchmark gate failed")
    if not scorecard_passed:
        errors.append("Scorecard runtime gate failed")

    report = {
        "generatedAt": datetime.now(UTC).isoformat(),
        "milestone": "M1 (85%)",
        "ready": ready,
        "estimatedCompletionPct": estimated_completion,
        "checks": checks,
        "context": {
            "dbSchemaVersion": schema_version.get("dbSchemaVersion"),
            "latestMigration": parse_latest_migration(),
            "retrievalRecallRate": retrieval_report.get("metrics", {}).get("retrievalRecallRate"),
            "retrievalDriftErrors": len(retrieval_report.get("driftErrors", [])),
            "scorecardCertificationStatus": scorecard_report.get("runtime", {}).get("scorecardCertificationStatus"),
            "scorecardMetricsCount": scorecard_report.get("runtime", {}).get("scorecardMetricsCount"),
        },
        "errors": errors,
        "logs": {
            "migration": migration_output,
            "retrieval": retrieval_output,
            "scorecard": scorecard_output,
        },
    }

    json_path = ARTIFACTS_DIR / "m1-readiness.json"
    md_path = ARTIFACTS_DIR / "m1-readiness.md"
    json_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(to_markdown(report), encoding="utf-8")

    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")
    print(f"Readiness: {'READY' if ready else 'NOT READY'}")
    print(f"Estimated completion: {estimated_completion}%")

    return 0 if ready else 1


if __name__ == "__main__":
    raise SystemExit(main())
