-- Index160 durable asynchronous Ollama review bridge.
ALTER TABLE local_worker_credentials ADD COLUMN IF NOT EXISTS capabilities JSONB NOT NULL DEFAULT '{}'::jsonb, ADD COLUMN IF NOT EXISTS worker_version TEXT, ADD COLUMN IF NOT EXISTS ollama_version TEXT, ADD COLUMN IF NOT EXISTS max_concurrent_jobs INTEGER NOT NULL DEFAULT 1;
ALTER TABLE llm_jobs DROP CONSTRAINT IF EXISTS llm_jobs_state_check;
ALTER TABLE llm_jobs ADD CONSTRAINT llm_jobs_state_check CHECK(state IN('queued','claimed','completed','failed','canceled','cancelled','retry_wait','superseded','expired'));
ALTER TABLE llm_jobs ADD COLUMN IF NOT EXISTS operation_id UUID, ADD COLUMN IF NOT EXISTS requested_model TEXT, ADD COLUMN IF NOT EXISTS requested_model_digest TEXT, ADD COLUMN IF NOT EXISTS lease_id UUID, ADD COLUMN IF NOT EXISTS lease_generation INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS workflow_stage TEXT NOT NULL DEFAULT 'queued', ADD COLUMN IF NOT EXISTS last_error JSONB;
CREATE TABLE ollama_review_operations(id UUID PRIMARY KEY,organization_id UUID NOT NULL DEFAULT ambrosia_current_organization_id() REFERENCES organizations(id) ON DELETE CASCADE,packet_id TEXT NOT NULL REFERENCES review_packet(packet_id) ON DELETE CASCADE,expected_packet_version INTEGER NOT NULL,semantic_key CHAR(64) NOT NULL,idempotency_key TEXT,state TEXT NOT NULL CHECK(state IN('queued','leased','running','verifying','repairing','retry_wait','completed','failed','expired','canceled','superseded')),stage TEXT NOT NULL,progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100),requested_provider TEXT NOT NULL DEFAULT 'ollama',actual_provider TEXT,requested_model TEXT,requested_model_digest TEXT,model_name TEXT,model_digest TEXT,worker_id UUID REFERENCES local_worker_credentials(id),job_id UUID REFERENCES llm_jobs(id),fallback_operation_id UUID REFERENCES ollama_review_operations(id),result_packet_version INTEGER,result_hash CHAR(64),error JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ,UNIQUE(organization_id,semantic_key),UNIQUE(organization_id,idempotency_key));
ALTER TABLE llm_jobs ADD CONSTRAINT llm_jobs_operation_id_fkey FOREIGN KEY(operation_id) REFERENCES ollama_review_operations(id) ON DELETE SET NULL;
CREATE TABLE llm_job_attempts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL DEFAULT ambrosia_current_organization_id() REFERENCES organizations(id) ON DELETE CASCADE,job_id UUID NOT NULL REFERENCES llm_jobs(id) ON DELETE CASCADE,worker_id UUID REFERENCES local_worker_credentials(id),attempt INTEGER NOT NULL,lease_id UUID NOT NULL,lease_generation INTEGER NOT NULL,state TEXT NOT NULL,started_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ,error JSONB,UNIQUE(job_id,lease_generation));
CREATE TABLE llm_operation_events(id BIGSERIAL PRIMARY KEY,organization_id UUID NOT NULL DEFAULT ambrosia_current_organization_id() REFERENCES organizations(id) ON DELETE CASCADE,operation_id UUID NOT NULL REFERENCES ollama_review_operations(id) ON DELETE CASCADE,event_type TEXT NOT NULL,stage TEXT,payload JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_ollama_operations_packet ON ollama_review_operations(organization_id,packet_id,created_at DESC); CREATE INDEX idx_llm_jobs_model_claim ON llm_jobs(organization_id,state,requested_model_digest,created_at) WHERE state='queued';
ALTER TABLE ollama_review_operations ENABLE ROW LEVEL SECURITY; ALTER TABLE llm_job_attempts ENABLE ROW LEVEL SECURITY; ALTER TABLE llm_operation_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ollama_review_operations USING(organization_id=ambrosia_current_organization_id()) WITH CHECK(organization_id=ambrosia_current_organization_id()); CREATE POLICY tenant_isolation ON llm_job_attempts USING(organization_id=ambrosia_current_organization_id()) WITH CHECK(organization_id=ambrosia_current_organization_id()); CREATE POLICY tenant_isolation ON llm_operation_events USING(organization_id=ambrosia_current_organization_id()) WITH CHECK(organization_id=ambrosia_current_organization_id());
GRANT SELECT,INSERT,UPDATE,DELETE ON ollama_review_operations,llm_job_attempts,llm_operation_events TO ambrosia_runtime; GRANT USAGE,SELECT ON SEQUENCE llm_operation_events_id_seq TO ambrosia_runtime;
